name: Build and deploy pages
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs: 
  build-pages-publish:
    name: Build html pages and publish
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout root files
        uses: actions/checkout@v4
        with:
          repository: tashima42/site-generator
          sparse-checkout: .
      - name: install site-generator
        run: |
          ./install.sh v0.0.5
          INSTALL_DIR=$HOME/.local/bin
          echo "${INSTALL_DIR}" >> "${GITHUB_PATH}"
      - name: build
        run: |
          site-generator generate -t tashima42 -d ./build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2